export const ADD_SERVICE = 'ADD_SERVICE';
export const REMOVE_SERVICE = 'REMOVE_SERVICE';
export const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';
// added
export const EDIT_SERVICE = 'EDIT_SERVICE';
export const CANCEL_SERVICE = 'CANCEL_SERVICE';
export const UPDATE_SERVICE = 'UPDATE_SERVICE';
// filter added
export const CHANGE_FILTER_FIELD = 'CHANGE_FILTER_FIELD';
export const FILTER_SERVICE = 'FILTER_SERVICE';
export const CANCEL_FILTER = 'CANCEL_FILTER';